services:
  migrator:
    container_name: migrator
    build:
      context: ./migrator
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-your_db}
      POSTGRES_USER: ${POSTGRES_USER:-your_nickname}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE:-disable}
      MIGRATIONS_PATH: file:///app/migrations
    volumes:
      - ./migrator/config.yml:/app/config.yml:ro
      - ./migrator/migrations:/app/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy
  order-service:
    container_name: order-service
    build:
      context: ./order-service
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-your_db}
      POSTGRES_USER: ${POSTGRES_USER:-your_nickname}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE:-disable}
    volumes:
      - ./order-service/config.yml:/app/config.yml:ro
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
  notify-service:
    container_name: notify-service
    build:
      context: ./notify-service
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-your_db}
      POSTGRES_USER: ${POSTGRES_USER:-your_nickname}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE:-disable}
    volumes:
      - ./notify-service/config.yml:/app/config.yml:ro
    depends_on:
      migrator:
        condition: service_completed_successfully
  postgres:
    container_name: postgres-app
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-your_nickname}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_password}
      POSTGRES_DB: ${POSTGRES_DB:-your_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5436:5432"
  
  zookeeper:
    container_name: kafka-zookeeper
    image: confluentinc/cp-zookeeper:7.7.8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    container_name: oms-kafka
    image: confluentinc/cp-kafka:7.7.8
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
  kafka-init:
    image: python:3.11
    volumes:
      - ./scripts/kafka/main.py:/app/main.py
    working_dir: /app
    command: >
      sh -c "pip install confluent-kafka && python main.py"
    depends_on:
      - kafka

volumes:
  postgres_data: